# SPDX-License-Identifier: MIT

version: 2
formats:
  - htmlzip
build:
  os: ubuntu-24.04
  tools:
    python: "3.9"
  jobs:
    create_environment:
      - asdf plugin add uv
      - asdf install uv latest
      - asdf global uv latest
      - UV_PROJECT_ENVIRONMENT=$READTHEDOCS_VIRTUALENV_PATH uv sync --no-default-groups --extra docs
    install:
      - "true"

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false
  builder: html
