# SPDX-License-Identifier: MIT

blank_issues_enabled: false
contact_links:
  - name: Discord Server
    about: Use our official Discord server to ask for help and questions as well.
    url: https://discord.gg/disnake
