# SPDX-License-Identifier: MIT

name: Set up environment
description: .
inputs:
  python-version:
    description: The python version to install
    required: true
outputs:
  python-version:
    description: The python version that was installed.
    value: ${{ steps.python-version.outputs.python-version }}

runs:
  using: composite
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true
        # this is the pinned version of python to use
        python-version: ${{ inputs.python-version }}

    - name: Install python
      shell: bash
      run: uv python install ${{ inputs.python-version }}

    - name: Cache pdm installation directory
      uses: actions/cache@v4
      with:
        path: ~/.cache/pdm
        key: ${{ runner.os }}-pdm-${{ inputs.python-version }}-${{ hashFiles('**/pyproject.toml') }}

    - name: Install pdm with uv
      shell: bash
      run: uv tool install --python 3.12 pdm==2.25.9

    - name: Disable PDM version check
      shell: bash
      run: |
        pdm config check_update false

    - name: Ignore saved pythons
      shell: bash
      run: |
        echo "PDM_IGNORE_SAVED_PYTHON=1" >> $GITHUB_ENV

    - name: Install nox
      shell: bash
      run: uv tool install nox

    - name: Set python version
      id: python-version
      shell: bash
      run: echo "python-version=$(python -c 'import sys; print(".".join(map(str,sys.version_info[:2])))')" >> $GITHUB_OUTPUT

    - name: Configure cache
      uses: ./.github/actions/cache-pdm
