# SPDX-License-Identifier: MIT

name: Set up environment
description: .
inputs:
  python-version:
    description: The python version to install
    required: true
outputs:
  python-version:
    description: The python version that was installed.
    value: ${{ steps.python-version.outputs.python-version }}

runs:
  using: composite
  steps:
    - name: Set up uv with python ${{ inputs.python-version }}
      id: setup-python
      uses: astral-sh/setup-uv@v6
      with:
        python-version: ${{ inputs.python-version }}
        version: "0.8.13"
        enable-cache: true

    - name: Set python version
      id: python-version
      shell: bash
      run: echo "python-version=$(uv run python -c 'import sys; print(".".join(map(str,sys.version_info[:2])))')" >> $GITHUB_OUTPUT

    - name: Configure cache
      uses: ./.github/actions/cache-uv
