# SPDX-License-Identifier: MIT

name: Set up environment
description: .
inputs:
  python-version:
    description: The python version to install
    required: false
    default: '3.10'
  use-cached-uv-lock:
    description: Whether to download the uv lock cache.
    required: false
    default: 'true'
  update-uv-lock:
    description: Whether to update the uv lock file. Allows the cache to fail.
    required: false
    default: 'false'
  uv-resolution-strategy:
    description: The uv resolution strategy to use. See https://docs.astral.sh/uv/reference/environment/#uv_resolution for details.
    required: false
    default: 'highest'
outputs:
  python-version:
    description: The python version that was installed.
    value: ${{ steps.python-version.outputs.python-version }}

runs:
  using: composite
  steps:
    - name: Download uv lock
      uses: actions/cache/restore@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
      if: ${{ inputs.use-cached-uv-lock != 'false' }}
      id: restore-uv-lock
      with:
        key: uv-lock-resolved-${{ inputs.uv-resolution-strategy }}
        path: uv.lock
        restore-keys: |
          uv-lock-resolved-${{ inputs.uv-resolution-strategy }}
        enableCrossOsArchive: true
        fail-on-cache-miss: ${{ inputs.update-uv-lock != 'true' }}

    - name: Set up uv with Python ${{ inputs.python-version }}
      id: setup-python
      uses: astral-sh/setup-uv@681c641aba71e4a1c380be3ab5e12ad51f415867 # v7.1.6
      with:
        version: '0.9.2'
        enable-cache: true
        # this doesn't install python but pins the uv version; its the same as providing UV_PYTHON
        python-version: ${{ inputs.python-version }}

    - name: Install Python ${{ inputs.python-version }}
      shell: bash
      env:
        UV_PYTHON_DOWNLOADS: automatic
        PYTHON_VERSION: ${{ inputs.python-version }}
      run: |
        uv python install ${PYTHON_VERSION}

    - name: Install nox
      shell: bash
      # This version should match the dependencies.nox version in noxfile.py's script metadata
      run: |
        uv tool install 'nox==2025.10.16'

    - name: Lock dependencies
      id: lock-uv-deps
      if: ${{ inputs.update-uv-lock }}
      shell: bash
      env:
        UV_LOCKED: 0
      run: uv lock --refresh

    - name: Set Python version
      id: python-version
      shell: bash
      env:
        UV_VENV_CLEAR: 1
      run: |
        uv venv .venv
        echo "python-version=$(uv run python -c 'import sys; print(".".join(map(str,sys.version_info[:2])))')" >> $GITHUB_OUTPUT
