name: ci

on: [push, pull_request]

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        cache: "pip"
        cache-dependency-path: |
          requirements/
          requirements.txt
          setup.py

    - name: Install requirements
      run: |
        python -m pip install nox
        nox -s setup -- tools

    - name: Run pre-commit
      uses: pre-commit/action@v2.0.3


  pyright:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
      fail-fast: false
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        cache: "pip"
        cache-dependency-path: |
          requirements/
          requirements.txt
          setup.py

    - name: Install requirements
      run: |
        python -m pip install nox
        nox -s setup

    - name: Set pyright version
      run: |
        PYRIGHT_VERSION="$(python -c 'import pyright; print(pyright.__pyright_version__)')"
        echo "PYRIGHT_VERSION=$PYRIGHT_VERSION" >> $GITHUB_ENV

    - name: Run pyright (Linux)
      uses: jakebailey/pyright-action@v1.0.3
      with:
        version: ${{ env.PYRIGHT_VERSION }}
        python-version: ${{ matrix.python-version }}
        python-platform: "Linux"
        no-comments: ${{ matrix.python-version != '3.8' }}  # only add comments for one version
        warnings: true

    - name: Run pyright (Windows)
      uses: jakebailey/pyright-action@v1.0.3
      if: ${{ success() || failure() }}  # run regardless of previous step's result
      with:
        version: ${{ env.PYRIGHT_VERSION }}
        python-version: ${{ matrix.python-version }}
        python-platform: "Windows"
        no-comments: true  # only add comments for one platform (see above)
        warnings: true


  slotscheck:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        cache: "pip"
        cache-dependency-path: |
          requirements/
          requirements.txt
          setup.py

    - name: Install requirements
      run: |
        python -m pip install nox
        nox -s setup -- tools

    - name: Run slotscheck
      run: task slotscheck

  pytest:
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        os: ["windows-latest", "ubuntu-latest"]
      fail-fast: true

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        cache: "pip"
        cache-dependency-path: |
          requirements/
          requirements.txt
          setup.py

    - name: Install requirements
      run: |
        python -m pip install nox

    - name: Test package install
      run: |
        python -m pip install .
        python -m pip uninstall -y disnake

    - name: Run pytest
      # use non-utc timezone, to test time/date-dependent features properly
      env:
        TZ: "America/New_York"
      run: nox -s test-${{ matrix.python-version }}
