name: test

on: [push, pull_request]

jobs:
  pytest:
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        os: ["windows-latest", "ubuntu-latest"]
      fail-fast: true

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        cache: "pip"
        cache-dependency-path: |
          requirements/
          requirements.txt
          setup.py

    - name: Install requirements
      run: |
        python -m pip install nox

    - name: Test package install
      run: |
        python -m pip install .
        python -m pip uninstall -y disnake

    - name: Run pytest
      # use non-utc timezone, to test time/date-dependent features properly
      env:
        TZ: "America/New_York"
      run: nox -s test-${{ matrix.python-version }}
