name: test

on: [push, pull_request]

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
      fail-fast: true
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        cache: "pip"
        cache-dependency-path: |
          requirements_dev.txt
          requirements.txt
          setup.py

    - name: Install requirements
      run: python -m pip install -r requirements.txt -r requirements_dev.txt

    - name: Run pytest
      run: task test
