# SPDX-License-Identifier: MIT

name: Configure PDM cache
description: .
inputs:
  env-already-initialized:
    description: Whether Python/PDM is already configured
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - name: Get metadata for cache
      id: get-cache-meta
      shell: bash
      run: |
        echo "date=$(date -u "+%Y%m%d")" >> $GITHUB_OUTPUT

    - name: Setup/Restore cache
      id: cache
      uses: actions/cache@v4
      with:
        path: |
          pdm.lock
        # cache lockfile for the current day, roughly
        key: pdm-${{ steps.get-cache-meta.outputs.date }}-${{ hashFiles('pyproject.toml') }}
        # pdm lockfiles should be platform-agnostic
        enableCrossOsArchive: true

    - if: ${{ steps.cache.outputs.cache-hit != 'true' && inputs.env-already-initialized != 'true' }}
      name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true

    - name: Cache pdm installation directory
      if: ${{ steps.cache.outputs.cache-hit != 'true' && inputs.env-already-initialized != 'true' }}
      uses: actions/cache@v4
      with:
        path: ~/.cache/pdm
        key: ${{ runner.os }}-pdm-${{ inputs.python-version }}-${{ hashFiles('**/pyproject.toml') }}

    - name: Install pdm with uv
      if: ${{ steps.cache.outputs.cache-hit != 'true' && inputs.env-already-initialized != 'true' }}
      shell: bash
      run: uv tool install --python 3.12 pdm==2.25.9

    - if: ${{ steps.cache.outputs.cache-hit != 'true' }}
      name: Lock all dependencies
      shell: bash
      run: |
        pdm lock -G:all  # create pdm.lock
